### ISSUE TITLE
Content license question

### ISSUE THREAD

**Issue by D4708** [twisterarmy/website#1]
Can I copy available [twister.net.co](url) content to create new unofficial community website / twister documentation?

**Comment by myleneb** [comment]
Miguel sent a .zip with full static content. Need to put this on github?

**Comment by D4708** [comment]
at least to archive it... https://github.com/twisterarmy/twister.net.co

**Comment by D4708** [comment]
Website materials should be licensed by Miguel before (MIT/GNU/CC etc) 

That is primary question. For example I wrote [Promotional draft](https://github.com/twisterarmy/documentation/wiki/Media-Resources) but not sure I have a rights too use that data, but more important, I can't license my derivative materials. 

Also we can publish static data using [GitHub Pages](https://pages.github.com/) feature.

**Comment by D4708** [comment]
Answered by Miguel https://github.com/miguelfreitas/twister-core/issues/447#issuecomment-789339568

Creative Commons License
